databases:
  - name: aub-db
    plan: free
    databaseName: aub_database
    user: aub_user

services:
  - type: web
    name: aub-project
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn aub_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.4"
